### ISSUE TITLE
Do we support version 1.5 of Urho3D?

### ISSUE THREAD

**Issue by kingofoz** [3dicc/Urhonimo#12]
Hello, 1.3.2 is pretty old now.

**Comment by kingofoz** [comment]
@gokr @Araq

**Comment by gokr** [comment]
Yeah, we know. We should sit down and redo the wrapper - Araq has some scripts for it, and ... we also did a bunch of manual edits after generating it, so ... those would have to be reapplied - but I think we could produce a patch first, between pristine wrapper from 1.32 -> our current wrapper for 1.32. And then try to reapply that patch on a newly generated wrapper for 1.5.

**Comment by kingofoz** [comment]
Fascinating. Please do it. I cannot wait to try Urhonimo. :-)

**Comment by kingofoz** [comment]
I can see some updates to the project now. I have below questions:
1. Urho3D-1.32 is useless now? Remove it and get 1.5 code of Urho3D?
2. Should I use the packed 1.5 code from https://github.com/urho3d/Urho3D/archive/1.5.zip or get the latest 1.5 code from the git head of Urho3D?
Thanks!

**Comment by kingofoz** [comment]
Close as solved.
