### ISSUE TITLE
Document the VC++ requirement on Windows

### ISSUE THREAD

**Issue by dom96** [3dicc/Urhonimo#2]
The readme makes no mention of requiring the Visual C++ compiler to compile on Windows. Perhaps it is possible to compile this via mingw? I tried but I got compilation errors.

Unfortunately using VC++ yielded even more errors for me. Do I need a specific version of it? I used the `cl.exe` in `C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin`.

I get a variety of errors but the following is common:

```
c:\Users\Dominik\git\nimrod\lib\nimbase.h(156) : fatal error C1083: Cannot open
include file: 'limits.h': No such file or directory
```

**Comment by gokr** [comment]
I guess the readme now covers the above at least.
